mobileapi:
    resource: "@MobileapiBundle/Resources/config/routing.yml"
    prefix:   /

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

prof:
    resource: "@ProfBundle/Resources/config/routing.yml"
    prefix:   /

gestion:
    resource: "@GestionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"